// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX5JskoU7kZ6NztE22P4RleAnCrr-KpL4',
    appId: '1:506336959167:web:56e39dd48a6dd775e9040a',
    messagingSenderId: '506336959167',
    projectId: 'demoproject-8f7ca',
    authDomain: 'demoproject-8f7ca.firebaseapp.com',
    storageBucket: 'demoproject-8f7ca.appspot.com',
    measurementId: 'G-1S3CJMWH4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwfhqhv3PXTfDc00vyTHBvnGzySrHGiY',
    appId: '1:506336959167:android:3a935888d06eb5b2e9040a',
    messagingSenderId: '506336959167',
    projectId: 'demoproject-8f7ca',
    storageBucket: 'demoproject-8f7ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkc-1mI8eQexzAOGq9ToCEUhyLpc-isfU',
    appId: '1:506336959167:ios:523c8eb9fea8622de9040a',
    messagingSenderId: '506336959167',
    projectId: 'demoproject-8f7ca',
    storageBucket: 'demoproject-8f7ca.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkc-1mI8eQexzAOGq9ToCEUhyLpc-isfU',
    appId: '1:506336959167:ios:523c8eb9fea8622de9040a',
    messagingSenderId: '506336959167',
    projectId: 'demoproject-8f7ca',
    storageBucket: 'demoproject-8f7ca.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX5JskoU7kZ6NztE22P4RleAnCrr-KpL4',
    appId: '1:506336959167:web:d91259ae94485286e9040a',
    messagingSenderId: '506336959167',
    projectId: 'demoproject-8f7ca',
    authDomain: 'demoproject-8f7ca.firebaseapp.com',
    storageBucket: 'demoproject-8f7ca.appspot.com',
    measurementId: 'G-PB3C88DHF3',
  );

}